"""worker: jobs.picked_up_at + pending_quizzes.job_id unique

Revision ID: 6003bece63a7
Revises: b32919fbbea3
Create Date: 2026-07-18 00:38:16.088189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6003bece63a7'
down_revision: Union[str, Sequence[str], None] = 'b32919fbbea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_quizzes', sa.Column('job_id', sa.Integer(), nullable=True))
    # UNIQUE is what makes worker retries idempotent: a job can only ever own
    # one pending_quizzes row (spec in progress.md).
    op.create_unique_constraint('uq_pending_quizzes_job_id', 'pending_quizzes', ['job_id'])
    op.create_foreign_key(
        'fk_pending_quizzes_job_id', 'pending_quizzes', 'quiz_generation_jobs',
        ['job_id'], ['id'],
    )
    op.add_column('quiz_generation_jobs', sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_generation_jobs', 'picked_up_at')
    op.drop_constraint('fk_pending_quizzes_job_id', 'pending_quizzes', type_='foreignkey')
    op.drop_constraint('uq_pending_quizzes_job_id', 'pending_quizzes', type_='unique')
    op.drop_column('pending_quizzes', 'job_id')
    # ### end Alembic commands ###
