"""initial schema

Revision ID: b32919fbbea3
Revises: 
Create Date: 2026-07-05 16:52:58.306057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32919fbbea3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('meaning_note', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('linguistic_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['global_dictionary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='quizstatus', native_enum=False, length=20), nullable=False),
    sa.Column('entity_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_quizzes_user_id'), 'pending_quizzes', ['user_id'], unique=False)
    op.create_table('quiz_generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('NEW_ITEM_ADDED', 'USER_ITEMS_DUE', name='jobeventtype', native_enum=False, length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', name='jobstatus', native_enum=False, length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_status_created', 'quiz_generation_jobs', ['status', 'created_at'], unique=False)
    op.create_table('user_mastery_matrix',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('repetition', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['global_dictionary.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'entity_id')
    )
    op.create_index(op.f('ix_user_mastery_matrix_next_review_date'), 'user_mastery_matrix', ['next_review_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mastery_matrix_next_review_date'), table_name='user_mastery_matrix')
    op.drop_table('user_mastery_matrix')
    op.drop_index('ix_jobs_status_created', table_name='quiz_generation_jobs')
    op.drop_table('quiz_generation_jobs')
    op.drop_index(op.f('ix_pending_quizzes_user_id'), table_name='pending_quizzes')
    op.drop_table('pending_quizzes')
    op.drop_table('users')
    op.drop_table('global_dictionary')
    # ### end Alembic commands ###
